### ISSUE TITLE
pac4j v4 compatibility

### ISSUE THREAD

**Issue by albert-kam** [pac4j/undertow-pac4j#34]
Hi pac4j team,

It seems that undertow-pac4j hasnt been updated to reflect the latest pac4j v4.x.x version.

I tried using the v4 of pac4j-core, with the pac4j-undertow v3.0.0 and this occurs:

```
java.lang.NoSuchMethodError: 'void org.pac4j.core.engine.DefaultSecurityLogic.setProfileManagerFactory(java.util.function.Function)'
	at org.pac4j.undertow.handler.SecurityHandler.<init>(SecurityHandler.java:48)
	at org.pac4j.undertow.handler.SecurityHandler.build(SecurityHandler.java:78)
	at org.pac4j.undertow.handler.SecurityHandler.build(SecurityHandler.java:74)
	at org.pac4j.undertow.handler.SecurityHandler.build(SecurityHandler.java:70)
	at org.pac4j.undertow.handler.SecurityHandler.build(SecurityHandler.java:66)
	at org.pac4j.undertow.handler.SecurityHandler.build(SecurityHandler.java:62)

```

Any plans to 'upgrade' this ?

Thank you !

**Comment by leleuj** [comment]
You won't be able to use pac4j v4 with the current undertow-pac4j version.

The upgrade is planned after vertx-pac4j, jax-rs-pac4j and dropwiazrd-pac4j (likely after the summer). Unless there is a business request or an open source contribution on this.

**Comment by leleuj** [comment]
Release coming soon
